### ISSUE TITLE
Something is missing in the source code

### ISSUE THREAD

**Issue by MawiaHL** [pomerla/OneSignal-Codeigniter-Push-Notification#1]
The code on the demo and the code in the GitHub seems different. For Instance, you did not provide the router for admin in the source code while it is in the demo. So the code does not work. If a user wants to go to admin, he needs to go to http://localhost/quotes.php. When we submit the form in the subcribe.php, we also get a json string **JSON sent: {"app_id":"10....}**. No Notification. Please can you put the code you used in the demo. You can remove the appid and rest api key. 

Regards,

**Comment by wpdew** [comment]
The code on GitHub is fully working. This is an example of the implementation of this task. The names of methods and controllers in the demo are different. The principle is the same.
Also, in the demo, a simple authorization check is added.
