### ISSUE TITLE
OneSignal

### ISSUE THREAD

**Issue by mdestafadilah** [pomerla/OneSignal-Codeigniter-Push-Notification#2]
Do you have config others in onesignal portal?

**Comment by wpdew** [comment]
That wasn't necessary.

**Comment by kardoaziz** [comment]
do you have any video ti show how to setup with and/or install to an existing project ?
I have an existing codeigniter project I want to send notification from its dashboard

**Comment by mdestafadilah** [comment]
just read doc, whats problem?
